### ISSUE TITLE
[BUG] no mime type for file extension xqs registered 

### ISSUE THREAD

**Issue by line-o** [eXist-db/node-exist#101]
```javascript
// exist specific mime types
mime.define({
  'application/xquery': ['xqs', 'xq', 'xql', 'xqm'],
  'application/xml': ['xconf', 'odd']
})

```

**Comment by joewiz** [comment]
There is also `.xqy` and `.xquery`. See https://github.com/eXist-db/atom-existdb/blob/master/grammars/xquery.cson#L2-L9. Technically, there's also `.xqws`, but it's hardly used. See https://markmail.org/message/25dsfjm53lk5q7h7.

**Comment by line-o** [comment]
Thanks, @joewiz will add `.xqy` (`.xquery` is already in there). If someone really wants xqws it can still be registered.
