### ISSUE TITLE
[BUG] misleading authentication error message

### ISSUE THREAD

**Issue by chakl** [eXist-db/node-exist#240]
**Describe the bug**

Looks like username `admin` is hardcoded in the authentication error message.

```
exsol:~$ npx -p @existdb/node-exist exist-ls /db/apps
Wrong password for user [admin] 
```
Forgot to pass credentials... Specify admin password via `EXISTDB_PASS` env var:
```
exsol:~$ env | grep EXIST
EXISTDB_PASS=MY_ADMIN_SECRET
exsol:~$ npx -p @existdb/node-exist exist-ls /db/apps
Wrong password for user [admin] 
```
Probably the default `guest` user is used for login, but why does it report "wrong pass for user admin"? Explicitly setting `EXISTDB_USER` works as expected.
```
exsol:~$ env | grep EXIST
EXISTDB_USER=admin
EXISTDB_PASS=MY_ADMIN_SECRET
exsol:~$ npx -p @existdb/node-exist exist-ls /db/apps
[... works ...]
```

**Expected behavior**
Report wrong password for the username that is actually used for authentication:
```
Wrong password for user [guest] 
```

**Context (please always complete the following information):**
- @existdb/node-exist@4.9.2
- node v16.15.1
- npm 8.11.0
- Debian 10

**Comment by line-o** [comment]
Sorry for that confusion. What you see is expected as the command line tools use a default connection to `admin` and the defaults are _only_ overridden if both environment variables are set (`EXISTDB_USER` _and_ `EXISTDB_PASS`)

**Comment by line-o** [comment]
You may also want to have a look at https://github.com/line-o/xst
It does default to the guest user as one would expect.

**Comment by line-o** [comment]
I just re-read the available documentation and it really fails to even mention that both environment variables have to be set in order to override the user.
So, should this be documented or the behaviour changed?
