### ISSUE TITLE
test failures for 4.2.1 and later

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/node-exist#3]
why would it expect `\n` [here](https://github.com/eXist-db/node-exist/blob/2820604657fd5cb3b136b7ebd4a71a40e86e1665/spec/tests/queries.js#L41) or is that what's being tested. 
We could prettify the response and remove the newlines from the expected results?

**Comment by line-o** [comment]
@duncdrum previous versions did output the resulting XML pretty-printed. This behaviour has changed since.
